#!/usr/bin/env bash
# lib/trace.sh - observe app needs and generate draft config
# shellcheck disable=SC2154  # _dir provided by adamas.sh

# --- metadata parser ---
# populates _T_* arrays from flatpak manifest metadata
_parse_metadata() {
  local app_id="$1"

  local meta
  meta="$(flatpak info --show-metadata "$app_id" 2>/dev/null)" \
    || die "cannot read metadata for $app_id"

  # reset trace arrays
  _T_SHARE=() _T_SOCKET=() _T_DEVICE=() _T_FEATURE=()
  _T_FILESYSTEM=() _T_PERSIST=()
  _T_DBUS_TALK=() _T_DBUS_OWN=()
  _T_SYSTEM_DBUS_TALK=() _T_SYSTEM_DBUS_OWN=()
  _T_DBUS_CALL=() _T_PORTAL=()

  local section="" key val
  while IFS= read -r line; do
    # section header
    if [[ "$line" =~ ^\[(.+)\]$ ]]; then
      section="${BASH_REMATCH[1]}"
      continue
    fi

    # skip empty lines and lines without =
    [[ "$line" == *=* ]] || continue
    key="${line%%=*}"
    val="${line#*=}"

    # --- [Context] ---
    if [[ "$section" == "Context" ]]; then
      local items item
      IFS=';' read -ra items <<< "$val"
      for item in "${items[@]}"; do
        [[ -n "$item" ]] || continue
        case "$key" in
          shared)     _T_SHARE+=("$item") ;;
          sockets)    _T_SOCKET+=("$item") ;;
          devices)    _T_DEVICE+=("$item") ;;
          features)   _T_FEATURE+=("$item") ;;
          filesystems) _T_FILESYSTEM+=("$item") ;;
          persistent) _T_PERSIST+=("$item") ;;
        esac
      done
    fi

    # --- [Session Bus Policy] ---
    if [[ "$section" == "Session Bus Policy" ]]; then
      case "$val" in
        own)  _T_DBUS_OWN+=("$key") ;;
        talk) _T_DBUS_TALK+=("$key") ;;
      esac
    fi

    # --- [System Bus Policy] ---
    if [[ "$section" == "System Bus Policy" ]]; then
      case "$val" in
        own)  _T_SYSTEM_DBUS_OWN+=("$key") ;;
        talk) _T_SYSTEM_DBUS_TALK+=("$key") ;;
      esac
    fi

    # [Environment] intentionally skipped - manifest env is package context, not user intent
  done <<< "$meta"
}

# --- conf renderer ---
# output draft .conf to stdout
_render_conf() {
  local app_id="$1"

  # helper: format array as (val1 val2) or ()
  _fmt_arr() {
    local -n _arr="$1"
    if [[ ${#_arr[@]} -eq 0 ]]; then
      printf '()'
    else
      printf '(%s)' "${_arr[*]}"
    fi
  }

  # helper: format array with quoting for multi-word entries
  _fmt_arr_quoted() {
    local -n _arr="$1"
    if [[ ${#_arr[@]} -eq 0 ]]; then
      printf '()'
      return
    fi
    local item
    printf '(\n'
    for item in "${_arr[@]}"; do
      printf '  "%s"\n' "$item"
    done
    printf ')'
  }

  printf '# generated by: adamas trace %s\n' "$app_id"
  printf '# source: flatpak info --show-metadata %s\n' "$app_id"
  printf '#\n'
  printf '# ⚠  this is a DRAFT - review before saving\n'
  printf '# ⚠  remove permissions the app does not need\n'
  printf '\n'
  printf 'APP_ID="%s"\n' "$app_id"

  printf '\n# --- share ---\n'
  printf 'ALLOW_SHARE=%s\n' "$(_fmt_arr _T_SHARE)"

  printf '\n# --- socket ---\n'
  printf 'ALLOW_SOCKET=%s\n' "$(_fmt_arr _T_SOCKET)"

  printf '\n# --- device ---\n'
  printf 'ALLOW_DEVICE=%s\n' "$(_fmt_arr _T_DEVICE)"

  printf '\n# --- feature ---\n'
  printf 'ALLOW_FEATURE=%s\n' "$(_fmt_arr _T_FEATURE)"

  printf '\n# --- filesystem ---\n'
  printf 'ALLOW_FILESYSTEM=%s\n' "$(_fmt_arr _T_FILESYSTEM)"

  printf '\n# --- session D-Bus ---\n'
  printf 'ALLOW_DBUS_TALK=%s\n' "$(_fmt_arr _T_DBUS_TALK)"
  printf 'ALLOW_DBUS_OWN=%s\n' "$(_fmt_arr _T_DBUS_OWN)"

  printf '\n# --- system D-Bus ---\n'
  printf 'ALLOW_SYSTEM_DBUS_TALK=%s\n' "$(_fmt_arr _T_SYSTEM_DBUS_TALK)"
  printf 'ALLOW_SYSTEM_DBUS_OWN=%s\n' "$(_fmt_arr _T_SYSTEM_DBUS_OWN)"

  printf '\n# --- a11y D-Bus ---\n'
  printf 'ALLOW_A11Y_OWN=()\n'

  printf '\n# --- USB ---\n'
  printf 'ALLOW_USB=()\n'

  printf '\n# --- persist ---\n'
  printf '# without this, app data lives in RAM and dies on exit\n'
  printf '# (.) = full disk | e.g. (.mozilla .config/app) = by name to disk\n'
  printf 'PERSIST=%s\n' "$(_fmt_arr _T_PERSIST)"

  printf '\n# --- policy ---\n'
  printf 'ADD_POLICY=()\n'

  printf '\n# --- env ---\n'
  printf '# baseline: HOME PATH XDG_RUNTIME_DIR DBUS_SESSION_BUS_ADDRESS\n'
  printf '#   WAYLAND_DISPLAY DISPLAY LANG\n'
  printf 'ALLOW_ENV=()\n'
  printf 'SET_ENV=()\n'

  printf '\n# --- portal ---\n'
  printf '# 8 denied by default: camera | microphone | speakers | location\n'
  printf '#   notifications | screenshot | screencast | background\n'
  printf 'ALLOW_PORTAL=%s\n' "$(_fmt_arr _T_PORTAL)"

  if [[ ${#_T_DBUS_CALL[@]} -gt 0 ]]; then
    printf '\n# --- D-Bus call filtering (runtime observed) ---\n'
    printf 'ALLOW_DBUS_CALL=%s\n' "$(_fmt_arr_quoted _T_DBUS_CALL)"
  fi
}

# --- save or print draft ---
_output_conf() {
  local app_id="$1" save="$2"
  if $save; then
    local name
    name="${app_id##*.}"
    name="${name,,}"
    local conf="${_dir}/apps/${name}.conf"
    if [[ -f "$conf" ]]; then
      name="${app_id//./-}"
      conf="${_dir}/apps/${name}.conf"
    fi
    [[ -f "$conf" ]] && die "config already exists: $conf"
    _render_conf "$app_id" > "$conf"
    ok "draft written: $conf"
  else
    _render_conf "$app_id"
  fi
}

# --- static analysis ---
_trace_static() {
  local app_id="$1" save="$2"
  _parse_metadata "$app_id"
  _output_conf "$app_id" "$save"
}

# --- trace (observe + generate draft) ---
adamas_trace() {
  local app_id="$1"; shift
  local save=false
  local arg
  for arg in "$@"; do
    case "$arg" in
      --save)    save=true ;;
      *)         die "unknown flag: $arg" ;;
    esac
  done

  _require_flatpak
  _is_installed "$app_id" || die "$app_id not installed"

  log "tracing ${app_id}..." >&2
  _trace_static "$app_id" "$save"
}
